// Generated by https://quicktype.io


export interface AllReposModel {
  organization: Organization;
}

export interface Organization {
  repositories: Repositories;
}

export interface Repositories {
  nodes: Node[];
  pageInfo: PageInfo;
}

export interface Node {
  name: string;
  id: string;
}



export interface PageInfo {
  endCursor: string;
  hasNextPage: boolean;
}
